import Head from "next/head";
import { signOut } from "next-auth/react";
import { Header } from "../components";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Linkin Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        {/* Sidebar */}
        <div></div>
        {/* Feed */}
        <div></div>
        {/* Widgets */}
        <div></div>
      </main>
    </div>
  );
}
